<a href="https://colab.research.google.com/github/francesco-vecchioli/colab/blob/main/torch-tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch  
torch.__version__

import numpy as np

In [2]:
from typing import Union

# Utility print function
def print_arr(*arr: Union[torch.Tensor, np.ndarray], prefix: str = "") -> None:
    """ Pretty print tensors, together with their shape and type
    
    :param arr: one or more tensors
    :param prefix: prefix to use when printing the tensors
    """
    print(
        "\n\n".join(
            f"{prefix}{str(x)} <shape: {x.shape}> <dtype: {x.dtype}>" for x in arr
        )
    )

In [29]:
v1 = torch.arange(0.0, 1.0, 0.1, dtype=torch.float64)
v2 = torch.arange(0.0, 0.6, 0.1, dtype=torch.float64)
out = v1[:, None] + v2[None, :]
print_arr(v1, v2, out)


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000], dtype=torch.float64) <shape: torch.Size([10])> <dtype: torch.float64>

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000], dtype=torch.float64) <shape: torch.Size([6])> <dtype: torch.float64>

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000],
        [0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000],
        [0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000],
        [0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000],
        [0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000],
        [0.5000, 0.6000, 0.7000, 0.8000, 0.9000, 1.0000],
        [0.6000, 0.7000, 0.8000, 0.9000, 1.0000, 1.1000],
        [0.7000, 0.8000, 0.9000, 1.0000, 1.1000, 1.2000],
        [0.8000, 0.9000, 1.0000, 1.1000, 1.2000, 1.3000],
        [0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000]], dtype=torch.float64) <shape: torch.Size([10, 6])> <dtype: torch.float64>


In [39]:
def lp(shape, a=5, b=1, p=1):
  x_arr = torch.arange(shape[0])[None, :]
  y_arr = torch.arange(shape[1])[:, None]
  return torch.pow(torch.pow(x_arr - a, p) + torch.pow(y_arr - b, p), 1/p)


print_arr(lp((10,3), p=0.3))

tensor([[    nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan,
             nan,     nan],
        [    nan,     nan,     nan,     nan,     nan,  0.0000,  1.0000,  2.0000,
          3.0000,  4.0000],
        [    nan,     nan,     nan,     nan,     nan,  1.0000, 10.0794, 14.5131,
         18.2626, 21.6540]]) <shape: torch.Size([3, 10])> <dtype: torch.float32>
